# Generated by Django 4.2.4 on 2025-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_attendance_url_attendee_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_id",
            field=models.IntegerField(default=1),
        ),
    ]
