# Generated by Django 4.2.4 on 2025-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_attendance_attendance_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="attendance_id",
        ),
        migrations.RemoveField(
            model_name="attendee",
            name="attendance",
        ),
    ]
