# Generated by Django 4.2.4 on 2025-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_remove_attendance_attendance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="att_id",
            field=models.IntegerField(default=1),
        ),
    ]
