# Generated by Django 4.2.4 on 2025-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_attendance_att_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PassKey",
        ),
        migrations.AddField(
            model_name="attendee",
            name="attendances",
            field=models.ManyToManyField(to="mainapp.attendance"),
        ),
        migrations.DeleteModel(
            name="RefImage",
        ),
    ]
